### PR TITLE
ready to merge 😉

### PR DESCRIPTION
**Pull request by jaspreet-singh-sahota**
###Newsweek-Clone
- To make a replica of newsweek.com.
- One of the main requirement of this project is to create a position: sticky;.
- Flex-box, grid and float bootstrap properties have been used mostly in the containers and some custom CSS.
- Eagerly waiting for the code review (P.S- One of the most challenging the projects I have worked on sofar )

### CODE REVIEW

**Comment by pelzolga123** [comment]
## Hi Jassi!  
### Great work so far :+1: 
But still not all requirements from previous reviews are met:
* [ ] Structure is still in wrong order:
* `Top story`
* `Culture & Travel`
* `More stories`
* `Opinion`
* `Latest news`
* `Featured stories`
#### Structure you should have:
* `Top story`
* `More stories`
* `Culture & Travel`
* `Featured stories`
* `Opinion`
* `Latest news`

* [ ] For medium screen next section is still messed up a little:
image

Original:
image

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by jaspreet-singh-sahota** [comment]
I hate bootstrap 😂😂😂

**Comment by kobiyoyo** [comment]
## Hi @jaspreet-singh-sahota        
#### Great Job so far, but there is one more thing to do. 
### Navbar
- [ ] You haven't implemented any change to the footer as stated by the previous TSE, let's fix that

### Make changes and submit another code review request.
*Happy coding*

**Comment by jaspreet-singh-sahota** [comment]
hopefully 5th times a Charm 🙏

**Pull request merged**
